### ISSUE TITLE
Realizar diagrama de espina de pescado

### ISSUE THREAD

**Issue by Wilmer-Ruiz** [Wilmer-Ruiz/equipo6_ijfr_ppi2020#1]
[diagrama espina de pescado.docx](https://github.com/Wilmer-Ruiz/equipo6_ijfr_ppi2020/files/4743382/diagrama.espina.de.pescado.docx)

**Comment by marthaduque** [comment]
se debe subir a la wiki y se debe mejorar la redacción del problema y revisar bien las causas que se tienen en las espina, ya que deben ser las causas que originan el problema actual.

**Comment by marthaduque** [comment]
SE DEBEN CORREGIR LAS CAUSAS DEL DIAGRAMA EN LO QUE SE REFIERE A ESTUDIANTES Y LIBROS
