### ISSUE TITLE
Declarar la situación del problema

### ISSUE THREAD

**Issue by Wilmer-Ruiz** [Wilmer-Ruiz/equipo6_ijfr_ppi2020#2]
[Declaración de la situación.docx](https://github.com/Wilmer-Ruiz/equipo6_ijfr_ppi2020/files/4743386/Declaracion.de.la.situacion.docx)

**Comment by marthaduque** [comment]
CORREGIR LA REDACCIÓN EN LA PARTE DE LA CONSECUENCIA DEL PROBLEMA.
